/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import modelo.PruebaFrecuencias;
import modelo.PruebaKolmogorov;
import modelo.PruebaPoker;
import modelo.PruebaPromedios;
import modelo.PruebaSeries;

/**
 *
 * @author Administrator
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    String[] listaPruebas={"Prueba de los promedios","Prueba de las frecuencias","Prueba de las series","Prueba Kolmogorov","Prueba del Poker"};
    PruebaPromedios promedios;
    PruebaFrecuencias frecuencia;
    PruebaSeries series;
    PruebaKolmogorov k_s;
    PruebaPoker poker;
    public VentanaPrincipal() {
        initComponents();
        this.setLocationRelativeTo(null);
        jComboSelect.setModel(new DefaultComboBoxModel<>(listaPruebas));
        
        jTextFieldK.setVisible(false);
        jLabelK.setText("");
        jLabelMensaje.setText(" ");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jPanelInicio = new javax.swing.JPanel();
        jLabelTitulo = new javax.swing.JLabel();
        jComboSelect = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaMuestra = new javax.swing.JTextArea();
        jTextFieldNivel = new javax.swing.JTextField();
        jButtonConcluir = new javax.swing.JButton();
        jLabelMensaje = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabelK = new javax.swing.JLabel();
        jTextFieldK = new javax.swing.JTextField();
        jButtonLimpiar = new javax.swing.JButton();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelInicio.setBackground(new java.awt.Color(0, 51, 51));
        jPanelInicio.setForeground(new java.awt.Color(255, 255, 255));

        jLabelTitulo.setBackground(new java.awt.Color(255, 255, 255));
        jLabelTitulo.setFont(new java.awt.Font("Haettenschweiler", 0, 48)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitulo.setText("Pruebas Estadisticas");

        jComboSelect.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboSelect.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboSelectItemStateChanged(evt);
            }
        });
        jComboSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboSelectActionPerformed(evt);
            }
        });

        jTextAreaMuestra.setColumns(20);
        jTextAreaMuestra.setRows(5);
        jScrollPane1.setViewportView(jTextAreaMuestra);

        jTextFieldNivel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNivelActionPerformed(evt);
            }
        });

        jButtonConcluir.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jButtonConcluir.setForeground(new java.awt.Color(0, 51, 255));
        jButtonConcluir.setText("concluir");
        jButtonConcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConcluirActionPerformed(evt);
            }
        });

        jLabelMensaje.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 16)); // NOI18N
        jLabelMensaje.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMensaje.setText("conclusion");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("datos de la muestra");

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("nivel de significancia");

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("selecciona una prueba");

        jLabelK.setForeground(new java.awt.Color(255, 255, 255));
        jLabelK.setText("valor K");

        jTextFieldK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldKActionPerformed(evt);
            }
        });

        jButtonLimpiar.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jButtonLimpiar.setForeground(new java.awt.Color(0, 51, 255));
        jButtonLimpiar.setText("limpiar");
        jButtonLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelInicioLayout = new javax.swing.GroupLayout(jPanelInicio);
        jPanelInicio.setLayout(jPanelInicioLayout);
        jPanelInicioLayout.setHorizontalGroup(
            jPanelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInicioLayout.createSequentialGroup()
                .addGroup(jPanelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelInicioLayout.createSequentialGroup()
                        .addGroup(jPanelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelInicioLayout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 478, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelInicioLayout.createSequentialGroup()
                                .addGap(178, 178, 178)
                                .addComponent(jLabel3)))
                        .addGroup(jPanelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelInicioLayout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addGroup(jPanelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanelInicioLayout.createSequentialGroup()
                                        .addComponent(jLabelK)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldK, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel4)
                                        .addComponent(jTextFieldNivel, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanelInicioLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanelInicioLayout.createSequentialGroup()
                                        .addComponent(jButtonConcluir)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButtonLimpiar))))))
                    .addGroup(jPanelInicioLayout.createSequentialGroup()
                        .addGap(187, 187, 187)
                        .addComponent(jLabelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelInicioLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(jPanelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jComboSelect, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanelInicioLayout.setVerticalGroup(
            jPanelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInicioLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabelTitulo)
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addGroup(jPanelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelInicioLayout.createSequentialGroup()
                        .addComponent(jTextFieldNivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelK))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonConcluir)
                            .addComponent(jButtonLimpiar))
                        .addGap(33, 33, 33)
                        .addComponent(jLabelMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelInicio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelInicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldNivelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNivelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNivelActionPerformed

    private void jButtonConcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConcluirActionPerformed
        // TODO add your handling code here:
        
        int selec=jComboSelect.getSelectedIndex();
        switch(selec){
            case 0: 
                System.out.println("prueba de los promedios");
                if(!jTextAreaMuestra.getText().isEmpty()&&!jTextFieldNivel.getText().isEmpty()){
                    try{
                        int nivel=Integer.parseInt(jTextFieldNivel.getText());
                        String muestra=jTextAreaMuestra.getText();
                        promedios= new PruebaPromedios(muestra,nivel);
                        if(promedios.concluir()){
                            jLabelMensaje.setText("UNIFORMIDAD");
                        }else{
                            jLabelMensaje.setText("NO UNIFORMIDAD");
                        }
                        
                    }catch(Exception e){
                        JOptionPane.showMessageDialog(null, "el nivel de significancia debe ser un numero entero");
                    }
                }else{
                    JOptionPane.showMessageDialog(null, "llene todos los campos");
                }
            break;
            case 1: 
                System.out.println("prueba de las frecuencias");
                if(!jTextAreaMuestra.getText().isEmpty()&&!jTextFieldNivel.getText().isEmpty()&&!jTextFieldK.getText().isEmpty()){
                    try{
                        int nivel=Integer.parseInt(jTextFieldNivel.getText());
                        int k =Integer.parseInt(jTextFieldK.getText());
                        String muestra=jTextAreaMuestra.getText();
                        frecuencia= new PruebaFrecuencias(muestra, k, nivel);
                        if(frecuencia.concluir()){
                            jLabelMensaje.setText("UNIFORMIDAD");
                        }else{
                            jLabelMensaje.setText("NO UNIFORMIDAD");
                        }
                        
                    }catch(Exception e){
                        JOptionPane.showMessageDialog(null, "el nivel de significancia y k debe ser un numero entero");
                    }
                }else{
                    JOptionPane.showMessageDialog(null, "llene todos los campos");
                }
            break;
            
            case 2:
                System.out.println("prueba de las series");
                if(!jTextAreaMuestra.getText().isEmpty()&&!jTextFieldNivel.getText().isEmpty()&&!jTextFieldK.getText().isEmpty()){
                    try{
                        int nivel=Integer.parseInt(jTextFieldNivel.getText());
                        int k =Integer.parseInt(jTextFieldK.getText());
                        String muestra=jTextAreaMuestra.getText();
                        series= new PruebaSeries(muestra, k, nivel);
                        if(series.concluir()){
                            jLabelMensaje.setText("INDEPENDENCIA");
                        }else{
                            jLabelMensaje.setText("NO INDEPENDENCIA");
                        }
                        
                    }catch(Exception e){
                        JOptionPane.showMessageDialog(null, "el nivel de significancia y k debe ser un numero entero");
                    }
                }else{
                    JOptionPane.showMessageDialog(null, "llene todos los campos");
                }
            break;
            
            case 3: 
                System.out.println("prueba kolmogorov");
                if(!jTextAreaMuestra.getText().isEmpty()&&!jTextFieldNivel.getText().isEmpty()){
                    try{
                        int nivel=Integer.parseInt(jTextFieldNivel.getText());
                        String muestra=jTextAreaMuestra.getText();
                        k_s= new PruebaKolmogorov(muestra, nivel);
                        if(k_s.concluir()){
                            jLabelMensaje.setText("UNIFORMIDAD");
                        }else{
                            jLabelMensaje.setText("NO UNIFORMIDAD");
                        }
                        
                    }catch(Exception e){
                        JOptionPane.showMessageDialog(null, "el nivel de significancia debe ser un numero entero");
                    }
                }else{
                    JOptionPane.showMessageDialog(null, "llene todos los campos");
                }
            break;
            
            case 4: 
                System.out.println("prueba del poker");
                if(!jTextAreaMuestra.getText().isEmpty()&&!jTextFieldNivel.getText().isEmpty()){
                    try{
                        int nivel=Integer.parseInt(jTextFieldNivel.getText());
                        String muestra=jTextAreaMuestra.getText();
                        poker= new PruebaPoker(muestra,nivel);
                        if(poker.concluir()){
                            jLabelMensaje.setText("INDEPENDENCIA");
                        }else{
                            jLabelMensaje.setText("NO INDEPENDENCIA");
                        }
                        
                    }catch(Exception e){
                        JOptionPane.showMessageDialog(null, "el nivel de significancia debe ser un numero entero");
                    }
                }else{
                    JOptionPane.showMessageDialog(null, "llene todos los campos");
                }
            break;
        }
        
    }//GEN-LAST:event_jButtonConcluirActionPerformed

    private void jComboSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboSelectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboSelectActionPerformed

    private void jComboSelectItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboSelectItemStateChanged
        // TODO add your handling code here:
        jTextAreaMuestra.setText("");
        jTextFieldNivel.setText("");
        jLabelMensaje.setText(" ");
        jTextFieldK.setText("");
        int selec=jComboSelect.getSelectedIndex();
        switch(selec){
            case 0 :
                jTextFieldK.setVisible(false);
                jLabelK.setText("");
            break;
            
            case 1: 
                jTextFieldK.setVisible(true);
                jLabelK.setText("valor K");
            break;
            
            case 2 : 
                jTextFieldK.setVisible(true);
                jLabelK.setText("valor K");
            break;
            
            case 3 :
                jTextFieldK.setVisible(false);
                jLabelK.setText("");
            break;
            
            case 4 :
                jTextFieldK.setVisible(false);
                jLabelK.setText("");
            break;
        }
    }//GEN-LAST:event_jComboSelectItemStateChanged

    private void jTextFieldKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldKActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldKActionPerformed

    private void jButtonLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimpiarActionPerformed
        // TODO add your handling code here:
        jTextAreaMuestra.setText("");
        jTextFieldNivel.setText("");
        jLabelMensaje.setText(" ");
        jTextFieldK.setText("");
    }//GEN-LAST:event_jButtonLimpiarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonConcluir;
    private javax.swing.JButton jButtonLimpiar;
    private javax.swing.JComboBox<String> jComboSelect;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelK;
    private javax.swing.JLabel jLabelMensaje;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JPanel jPanelInicio;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaMuestra;
    private javax.swing.JTextField jTextFieldK;
    private javax.swing.JTextField jTextFieldNivel;
    // End of variables declaration//GEN-END:variables
}
